# Generated by Django 3.0 on 2020-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Предложение')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('date_init', models.DateTimeField(null=True, verbose_name='Время подачи')),
                ('status', models.BooleanField(verbose_name='Статус исполнения')),
                ('date_exec', models.DateTimeField(null=True, verbose_name='Время Исполнения')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, null=True, verbose_name='Фамилия')),
                ('second_Name', models.CharField(max_length=200, null=True, verbose_name='Отчество')),
                ('voices', models.IntegerField(null=True, verbose_name='Голоса')),
                ('place', models.CharField(max_length=200, null=True, verbose_name='Город (Район)')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='Телефон')),
                ('voice_status', models.BooleanField(verbose_name='Мой голос')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
